Payroll.UI/Controllers/MonthsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Payroll.DAL;
using Payroll.Entities.Models;
using Payroll.Logic.Initializations;
using Payroll.Logic.Calculations;
using Microsoft.AspNet.Identity;
using Payroll.Entities.ViewModels;
using Payroll.Entities;
using System.Web.Script.Serialization;
using Payroll.UI.Models;
using Payroll.Logger.Common;

namespace Payroll.UI.Controllers
{
    public class MonthsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Months
        public ActionResult Index()
        {
            //try
            //{
            //    throw new Exception();
            //}
            //catch (Exception ex)
            //{
            //    StaticLogger.LogWarn(ex, "instance warn");
            //    StaticLogger.LogError(ex, "instance error");
            //    StaticLogger.LogFatal(ex, "instance fatal");
            //}

            var date = new SelectMonthVM();
            date.DateTime = DateTime.Now.ToShortDateString();

            return View(date);
        }

        // GET: Months/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Month month = db.Months.Find(id);
            if (month == null)
            {
                return HttpNotFound();
            }
            return View(month);
        }

        // GET: Months/Create
        [HttpGet]
        public ActionResult Create([Bind(Include = "DateTime")] SelectMonthVM SelectMonthVM)
        {
            var initialInput= new InputData();
            ViewData["Currency"] = initialInput.Currency();
            ViewData["LeaveDay"] = initialInput.LeaveTypes();

            MonthInitialization newMonth = new MonthInitialization();
            var Month = newMonth.MonthConstructor(Convert.ToDateTime(SelectMonthVM.DateTime), User.Identity.GetUserId());

            var salaryMonth = AutoMapper.Mapper.Map<SalaryMonthViewModel>(Month);
            return View(salaryMonth);
        }

        // POST: Months/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Name,TotalHours,OvertimeMonthHours,TotalNationalHolidays,TotalMaternityLeaves,TotalMedicalLeaves,TotalUnpaidLeaves,Weeks,Salary,Currency")] SalaryMonthViewModel inputSalaryMonthData)
        {
            if (ModelState.IsValid)
            {
                //Hours and Salary Calc
                var userMonth = new MonthCalc();
                userMonth.TimePeriodCalculations(inputSalaryMonthData);

                var SalaryMonth = AutoMapper.Mapper.Map<Salary>(inputSalaryMonthData);
                userMonth.SalaryCalculations(SalaryMonth);
                //if (!String.IsNullOrEmpty(User.Identity.GetUserId()))  //TODO uncomment after tests on save month
                //userMonth.InsertIntoDb(SalaryMonth);

                return RedirectToAction("Index");
            }

            return View(inputSalaryMonthData);
        }

        // GET: Months/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Month month = db.Months.Find(id);
            if (month == null)
            {
                return HttpNotFound();
            }
            return View(month);
        }

        // POST: Months/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Name,TotalHours,OvertimeMonthHours,TotalNationalHolidays,TotalMaternityLeaves,TotalMedicalLeaves,TotalUnpaidLeaves")] Month month)
        {
            if (ModelState.IsValid)
            {
                db.Entry(month).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(month);
        }

        // GET: Months/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Month month = db.Months.Find(id);
            if (month == null)
            {
                return HttpNotFound();
            }
            return View(month);
        }

        // POST: Months/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Month month = db.Months.Find(id);
            db.Months.Remove(month);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Payroll.UI/Views/Shared/_GetMonthPArtial.cshtml
@model Payroll.Entities.Models.Month
<link href="~/Content/Month.css" rel="stylesheet" />

@*<script type="text/javascript">
    var ModelObj = @Html.Raw(Json.Encode(Model)); //Save javascript object/model to use in script/month.js
</script>*@

@Html.HiddenFor(model => model.UserId)
@Html.HiddenFor(model => model.Name)
@Html.HiddenFor(model => model.TotalHours)
@Html.HiddenFor(model => model.OvertimeMonthHours)
@Html.HiddenFor(model => model.TotalNationalHolidays)
@Html.HiddenFor(model => model.TotalMaternityLeaves)
@Html.HiddenFor(model => model.TotalMedicalLeaves)
@Html.HiddenFor(model => model.TotalUnpaidLeaves)

@for (int i = 0; i < Model.Weeks.Count; i++)
{
    <div class="container">
        <div class="row seven-cols">

            @for (int j = 0; j < Model.Weeks[i].Days.Count(); j++)
            {
                @Html.HiddenFor(model => model.Weeks[i].Days[j].Date)
                @Html.HiddenFor(model => model.Weeks[i].Days[j].DayOfWeek)
                <div class="col-md-1">
                    <div class="thumbnail" style="background-color: #a7e6e8">

                        @Html.LabelFor(model => model.Weeks[i].Days[j].DayOfWeek, Model.Weeks[i].Days[j].DayOfWeek, htmlAttributes: new { @class = "control-label col-md-12"})
                        @Html.LabelFor(model => model.Weeks[i].Days[j].Date, Model.Weeks[i].Days[j].Date, htmlAttributes: new { @class = "control-label col-md-12" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.Weeks[i].Days[j].FirstShift, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Weeks[i].Days[j].FirstShift, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Weeks[i].Days[j].FirstShift, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Weeks[i].Days[j].SecondShift, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Weeks[i].Days[j].SecondShift, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Weeks[i].Days[j].SecondShift, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Weeks[i].Days[j].ThirdShift, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Weeks[i].Days[j].ThirdShift, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Weeks[i].Days[j].ThirdShift, "", new { @class = "text-danger" })
                            </div>
                        </div>

                          @Html.HiddenFor(model => model.Weeks[i].Days[j].IsNationalHoliday)
                          @Html.HiddenFor(model => model.Weeks[i].Days[j].IsMaternityLeave)
                          @Html.HiddenFor(model => model.Weeks[i].Days[j].IsMedicalLeave)
                          @Html.HiddenFor(model => model.Weeks[i].Days[j].isUnpdaidLeave)
                                  
                        @Html.DropDownList($"DropDown-{i}-{j}", ViewData["LeaveDay"] as List<SelectListItem> , new { onchange = $"DropDownChange({i},{j});"})

                    </div>
                </div>

            }
        </div>
    </div>
    <br />
}

Payroll.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Calendar", "Index", "Months")</li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"
            integrity="sha256-DI6NdAhhFRnO2k51mumYeDShet3I8AKCQf/tf7ARNhI="
            crossorigin="anonymous"></script>

    @RenderSection("scripts", required: false)
</body>
</html>